# Generated by Django 5.2.17 on 2026-09-04 08:02

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("candidate", models.CharField(blank=True, max_length=120)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("duration_minutes", models.PositiveIntegerField(default=120)),
                ("order", models.JSONField(default=list)),
                ("answers", models.JSONField(default=dict)),
                ("flagged", models.JSONField(default=list)),
                ("scaled_score", models.PositiveIntegerField(blank=True, null=True)),
                ("raw_correct", models.PositiveIntegerField(blank=True, null=True)),
                ("passed", models.BooleanField(blank=True, null=True)),
                ("auto_submitted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField(unique=True)),
                ("scenario", models.CharField(max_length=120)),
                ("domain", models.CharField(max_length=4)),
                (
                    "qtype",
                    models.CharField(
                        choices=[
                            ("single", "Multiple choice"),
                            ("multi", "Multiple response"),
                        ],
                        default="single",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField()),
                ("option_a", models.TextField()),
                ("option_b", models.TextField()),
                ("option_c", models.TextField()),
                ("option_d", models.TextField()),
                (
                    "correct",
                    models.CharField(
                        help_text="Comma-separated letters, e.g. 'A' or 'A,B'",
                        max_length=10,
                    ),
                ),
                ("explanation", models.TextField()),
            ],
            options={
                "ordering": ["number"],
            },
        ),
    ]
