# Generated by Django 5.2.17 on 2026-09-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_attempt_pause_and_presentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='form_type',
            field=models.CharField(choices=[('full', 'Full exam'), ('short', 'Short practice')], default='full', max_length=10),
        ),
    ]
